// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 4.26.1
package com.google.ai.edge.gallery.proto;

public interface ImportedModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.ai.edge.gallery.proto.ImportedModel)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int64 file_size = 2;</code>
   * @return The fileSize.
   */
  long getFileSize();

  /**
   * <code>.com.google.ai.edge.gallery.proto.LlmConfig llm_config = 3;</code>
   * @return Whether the llmConfig field is set.
   */
  boolean hasLlmConfig();
  /**
   * <code>.com.google.ai.edge.gallery.proto.LlmConfig llm_config = 3;</code>
   * @return The llmConfig.
   */
  com.google.ai.edge.gallery.proto.LlmConfig getLlmConfig();

  public com.google.ai.edge.gallery.proto.ImportedModel.ConfigCase getConfigCase();
}
