// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto
// Protobuf Java Version: 4.26.1

package com.google.ai.edge.gallery.proto;

public final class SettingsOuterClass {
  private SettingsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
