// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 4.26.1
package com.google.ai.edge.gallery.proto;

public interface SettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.ai.edge.gallery.proto.Settings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   * @return The enum numeric value on the wire for theme.
   */
  int getThemeValue();
  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   * @return The theme.
   */
  com.google.ai.edge.gallery.proto.Theme getTheme();

  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   * @return Whether the accessTokenData field is set.
   */
  boolean hasAccessTokenData();
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   * @return The accessTokenData.
   */
  com.google.ai.edge.gallery.proto.AccessTokenData getAccessTokenData();

  /**
   * <code>repeated string text_input_history = 3;</code>
   * @return A list containing the textInputHistory.
   */
  java.util.List<java.lang.String>
      getTextInputHistoryList();
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @return The count of textInputHistory.
   */
  int getTextInputHistoryCount();
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param index The index of the element to return.
   * @return The textInputHistory at the given index.
   */
  java.lang.String getTextInputHistory(int index);
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param index The index of the element to return.
   * @return The textInputHistory at the given index.
   */
  com.google.protobuf.ByteString
      getTextInputHistoryBytes(int index);

  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  java.util.List<com.google.ai.edge.gallery.proto.ImportedModel> 
      getImportedModelList();
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  com.google.ai.edge.gallery.proto.ImportedModel getImportedModel(int index);
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  int getImportedModelCount();

  /**
   * <code>bool is_tos_accepted = 5;</code>
   * @return The isTosAccepted.
   */
  boolean getIsTosAccepted();
}
