// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 4.26.1
package com.google.ai.edge.gallery.proto;

/**
 * Protobuf type {@code com.google.ai.edge.gallery.proto.Settings}
 */
public  final class Settings extends
    com.google.protobuf.GeneratedMessageLite<
        Settings, Settings.Builder> implements
    // @@protoc_insertion_point(message_implements:com.google.ai.edge.gallery.proto.Settings)
    SettingsOrBuilder {
  private Settings() {
    textInputHistory_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    importedModel_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int THEME_FIELD_NUMBER = 1;
  private int theme_;
  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   * @return The enum numeric value on the wire for theme.
   */
  @java.lang.Override
  public int getThemeValue() {
    return theme_;
  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   * @return The theme.
   */
  @java.lang.Override
  public com.google.ai.edge.gallery.proto.Theme getTheme() {
    com.google.ai.edge.gallery.proto.Theme result = com.google.ai.edge.gallery.proto.Theme.forNumber(theme_);
    return result == null ? com.google.ai.edge.gallery.proto.Theme.UNRECOGNIZED : result;
  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   * @param value The enum numeric value on the wire for theme to set.
   */
  private void setThemeValue(int value) {
      theme_ = value;
  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   * @param value The theme to set.
   */
  private void setTheme(com.google.ai.edge.gallery.proto.Theme value) {
    theme_ = value.getNumber();

  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
   */
  private void clearTheme() {

    theme_ = 0;
  }

  public static final int ACCESS_TOKEN_DATA_FIELD_NUMBER = 2;
  private com.google.ai.edge.gallery.proto.AccessTokenData accessTokenData_;
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   */
  @java.lang.Override
  public boolean hasAccessTokenData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   */
  @java.lang.Override
  public com.google.ai.edge.gallery.proto.AccessTokenData getAccessTokenData() {
    return accessTokenData_ == null ? com.google.ai.edge.gallery.proto.AccessTokenData.getDefaultInstance() : accessTokenData_;
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   */
  private void setAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
    value.getClass();
  accessTokenData_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
    value.getClass();
  if (accessTokenData_ != null &&
        accessTokenData_ != com.google.ai.edge.gallery.proto.AccessTokenData.getDefaultInstance()) {
      accessTokenData_ =
        com.google.ai.edge.gallery.proto.AccessTokenData.newBuilder(accessTokenData_).mergeFrom(value).buildPartial();
    } else {
      accessTokenData_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
   */
  private void clearAccessTokenData() {  accessTokenData_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int TEXT_INPUT_HISTORY_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> textInputHistory_;
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @return A list containing the textInputHistory.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getTextInputHistoryList() {
    return textInputHistory_;
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @return The count of textInputHistory.
   */
  @java.lang.Override
  public int getTextInputHistoryCount() {
    return textInputHistory_.size();
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param index The index of the element to return.
   * @return The textInputHistory at the given index.
   */
  @java.lang.Override
  public java.lang.String getTextInputHistory(int index) {
    return textInputHistory_.get(index);
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the textInputHistory at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextInputHistoryBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        textInputHistory_.get(index));
  }
  private void ensureTextInputHistoryIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        textInputHistory_;  if (!tmp.isModifiable()) {
      textInputHistory_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param index The index to set the value at.
   * @param value The textInputHistory to set.
   */
  private void setTextInputHistory(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureTextInputHistoryIsMutable();
    textInputHistory_.set(index, value);
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param value The textInputHistory to add.
   */
  private void addTextInputHistory(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureTextInputHistoryIsMutable();
    textInputHistory_.add(value);
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param values The textInputHistory to add.
   */
  private void addAllTextInputHistory(
      java.lang.Iterable<java.lang.String> values) {
    ensureTextInputHistoryIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, textInputHistory_);
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   */
  private void clearTextInputHistory() {
    textInputHistory_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string text_input_history = 3;</code>
   * @param value The bytes of the textInputHistory to add.
   */
  private void addTextInputHistoryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureTextInputHistoryIsMutable();
    textInputHistory_.add(value.toStringUtf8());
  }

  public static final int IMPORTED_MODEL_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.google.ai.edge.gallery.proto.ImportedModel> importedModel_;
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.ai.edge.gallery.proto.ImportedModel> getImportedModelList() {
    return importedModel_;
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  public java.util.List<? extends com.google.ai.edge.gallery.proto.ImportedModelOrBuilder> 
      getImportedModelOrBuilderList() {
    return importedModel_;
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  @java.lang.Override
  public int getImportedModelCount() {
    return importedModel_.size();
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  @java.lang.Override
  public com.google.ai.edge.gallery.proto.ImportedModel getImportedModel(int index) {
    return importedModel_.get(index);
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  public com.google.ai.edge.gallery.proto.ImportedModelOrBuilder getImportedModelOrBuilder(
      int index) {
    return importedModel_.get(index);
  }
  private void ensureImportedModelIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.ai.edge.gallery.proto.ImportedModel> tmp = importedModel_;
    if (!tmp.isModifiable()) {
      importedModel_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  private void setImportedModel(
      int index, com.google.ai.edge.gallery.proto.ImportedModel value) {
    value.getClass();
  ensureImportedModelIsMutable();
    importedModel_.set(index, value);
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  private void addImportedModel(com.google.ai.edge.gallery.proto.ImportedModel value) {
    value.getClass();
  ensureImportedModelIsMutable();
    importedModel_.add(value);
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  private void addImportedModel(
      int index, com.google.ai.edge.gallery.proto.ImportedModel value) {
    value.getClass();
  ensureImportedModelIsMutable();
    importedModel_.add(index, value);
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  private void addAllImportedModel(
      java.lang.Iterable<? extends com.google.ai.edge.gallery.proto.ImportedModel> values) {
    ensureImportedModelIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, importedModel_);
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  private void clearImportedModel() {
    importedModel_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
   */
  private void removeImportedModel(int index) {
    ensureImportedModelIsMutable();
    importedModel_.remove(index);
  }

  public static final int IS_TOS_ACCEPTED_FIELD_NUMBER = 5;
  private boolean isTosAccepted_;
  /**
   * <code>bool is_tos_accepted = 5;</code>
   * @return The isTosAccepted.
   */
  @java.lang.Override
  public boolean getIsTosAccepted() {
    return isTosAccepted_;
  }
  /**
   * <code>bool is_tos_accepted = 5;</code>
   * @param value The isTosAccepted to set.
   */
  private void setIsTosAccepted(boolean value) {
    
    isTosAccepted_ = value;
  }
  /**
   * <code>bool is_tos_accepted = 5;</code>
   */
  private void clearIsTosAccepted() {

    isTosAccepted_ = false;
  }

  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.ai.edge.gallery.proto.Settings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.ai.edge.gallery.proto.Settings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.ai.edge.gallery.proto.Settings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.ai.edge.gallery.proto.Settings prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.google.ai.edge.gallery.proto.Settings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.ai.edge.gallery.proto.Settings, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.ai.edge.gallery.proto.Settings)
      com.google.ai.edge.gallery.proto.SettingsOrBuilder {
    // Construct using com.google.ai.edge.gallery.proto.Settings.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
     * @return The enum numeric value on the wire for theme.
     */
    @java.lang.Override
    public int getThemeValue() {
      return instance.getThemeValue();
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
     * @param value The theme to set.
     * @return This builder for chaining.
     */
    public Builder setThemeValue(int value) {
      copyOnWrite();
      instance.setThemeValue(value);
      return this;
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
     * @return The theme.
     */
    @java.lang.Override
    public com.google.ai.edge.gallery.proto.Theme getTheme() {
      return instance.getTheme();
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
     * @param value The enum numeric value on the wire for theme to set.
     * @return This builder for chaining.
     */
    public Builder setTheme(com.google.ai.edge.gallery.proto.Theme value) {
      copyOnWrite();
      instance.setTheme(value);
      return this;
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.Theme theme = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTheme() {
      copyOnWrite();
      instance.clearTheme();
      return this;
    }

    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
     */
    @java.lang.Override
    public boolean hasAccessTokenData() {
      return instance.hasAccessTokenData();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
     */
    @java.lang.Override
    public com.google.ai.edge.gallery.proto.AccessTokenData getAccessTokenData() {
      return instance.getAccessTokenData();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
     */
    public Builder setAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
      copyOnWrite();
      instance.setAccessTokenData(value);
      return this;
      }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
     */
    public Builder setAccessTokenData(
        com.google.ai.edge.gallery.proto.AccessTokenData.Builder builderForValue) {
      copyOnWrite();
      instance.setAccessTokenData(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
     */
    public Builder mergeAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
      copyOnWrite();
      instance.mergeAccessTokenData(value);
      return this;
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 2;</code>
     */
    public Builder clearAccessTokenData() {  copyOnWrite();
      instance.clearAccessTokenData();
      return this;
    }

    /**
     * <code>repeated string text_input_history = 3;</code>
     * @return A list containing the textInputHistory.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getTextInputHistoryList() {
      return java.util.Collections.unmodifiableList(
          instance.getTextInputHistoryList());
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @return The count of textInputHistory.
     */
    @java.lang.Override
    public int getTextInputHistoryCount() {
      return instance.getTextInputHistoryCount();
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @param index The index of the element to return.
     * @return The textInputHistory at the given index.
     */
    @java.lang.Override
    public java.lang.String getTextInputHistory(int index) {
      return instance.getTextInputHistory(index);
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the textInputHistory at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextInputHistoryBytes(int index) {
      return instance.getTextInputHistoryBytes(index);
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @param index The index to set the value at.
     * @param value The textInputHistory to set.
     * @return This builder for chaining.
     */
    public Builder setTextInputHistory(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setTextInputHistory(index, value);
      return this;
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @param value The textInputHistory to add.
     * @return This builder for chaining.
     */
    public Builder addTextInputHistory(
        java.lang.String value) {
      copyOnWrite();
      instance.addTextInputHistory(value);
      return this;
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @param values The textInputHistory to add.
     * @return This builder for chaining.
     */
    public Builder addAllTextInputHistory(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllTextInputHistory(values);
      return this;
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextInputHistory() {
      copyOnWrite();
      instance.clearTextInputHistory();
      return this;
    }
    /**
     * <code>repeated string text_input_history = 3;</code>
     * @param value The bytes of the textInputHistory to add.
     * @return This builder for chaining.
     */
    public Builder addTextInputHistoryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addTextInputHistoryBytes(value);
      return this;
    }

    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.ai.edge.gallery.proto.ImportedModel> getImportedModelList() {
      return java.util.Collections.unmodifiableList(
          instance.getImportedModelList());
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    @java.lang.Override
    public int getImportedModelCount() {
      return instance.getImportedModelCount();
    }/**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    @java.lang.Override
    public com.google.ai.edge.gallery.proto.ImportedModel getImportedModel(int index) {
      return instance.getImportedModel(index);
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder setImportedModel(
        int index, com.google.ai.edge.gallery.proto.ImportedModel value) {
      copyOnWrite();
      instance.setImportedModel(index, value);
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder setImportedModel(
        int index, com.google.ai.edge.gallery.proto.ImportedModel.Builder builderForValue) {
      copyOnWrite();
      instance.setImportedModel(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder addImportedModel(com.google.ai.edge.gallery.proto.ImportedModel value) {
      copyOnWrite();
      instance.addImportedModel(value);
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder addImportedModel(
        int index, com.google.ai.edge.gallery.proto.ImportedModel value) {
      copyOnWrite();
      instance.addImportedModel(index, value);
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder addImportedModel(
        com.google.ai.edge.gallery.proto.ImportedModel.Builder builderForValue) {
      copyOnWrite();
      instance.addImportedModel(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder addImportedModel(
        int index, com.google.ai.edge.gallery.proto.ImportedModel.Builder builderForValue) {
      copyOnWrite();
      instance.addImportedModel(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder addAllImportedModel(
        java.lang.Iterable<? extends com.google.ai.edge.gallery.proto.ImportedModel> values) {
      copyOnWrite();
      instance.addAllImportedModel(values);
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder clearImportedModel() {
      copyOnWrite();
      instance.clearImportedModel();
      return this;
    }
    /**
     * <code>repeated .com.google.ai.edge.gallery.proto.ImportedModel imported_model = 4;</code>
     */
    public Builder removeImportedModel(int index) {
      copyOnWrite();
      instance.removeImportedModel(index);
      return this;
    }

    /**
     * <code>bool is_tos_accepted = 5;</code>
     * @return The isTosAccepted.
     */
    @java.lang.Override
    public boolean getIsTosAccepted() {
      return instance.getIsTosAccepted();
    }
    /**
     * <code>bool is_tos_accepted = 5;</code>
     * @param value The isTosAccepted to set.
     * @return This builder for chaining.
     */
    public Builder setIsTosAccepted(boolean value) {
      copyOnWrite();
      instance.setIsTosAccepted(value);
      return this;
    }
    /**
     * <code>bool is_tos_accepted = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsTosAccepted() {
      copyOnWrite();
      instance.clearIsTosAccepted();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.google.ai.edge.gallery.proto.Settings)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.ai.edge.gallery.proto.Settings();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "theme_",
            "accessTokenData_",
            "textInputHistory_",
            "importedModel_",
            com.google.ai.edge.gallery.proto.ImportedModel.class,
            "isTosAccepted_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0002\u0000\u0001\f\u0002\u1009" +
              "\u0000\u0003\u021a\u0004\u001b\u0005\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.ai.edge.gallery.proto.Settings> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.ai.edge.gallery.proto.Settings.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.ai.edge.gallery.proto.Settings>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.google.ai.edge.gallery.proto.Settings)
  private static final com.google.ai.edge.gallery.proto.Settings DEFAULT_INSTANCE;
  static {
    Settings defaultInstance = new Settings();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Settings.class, defaultInstance);
  }

  public static com.google.ai.edge.gallery.proto.Settings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Settings> PARSER;

  public static com.google.protobuf.Parser<Settings> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

