// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 4.26.1
package com.google.ai.edge.gallery.proto;

public interface UserDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.ai.edge.gallery.proto.UserData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   * @return Whether the accessTokenData field is set.
   */
  boolean hasAccessTokenData();
  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   * @return The accessTokenData.
   */
  com.google.ai.edge.gallery.proto.AccessTokenData getAccessTokenData();
}
