// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

// Protobuf Java Version: 4.26.1
package com.google.ai.edge.gallery.proto;

/**
 * Protobuf type {@code com.google.ai.edge.gallery.proto.UserData}
 */
public  final class UserData extends
    com.google.protobuf.GeneratedMessageLite<
        UserData, UserData.Builder> implements
    // @@protoc_insertion_point(message_implements:com.google.ai.edge.gallery.proto.UserData)
    UserDataOrBuilder {
  private UserData() {
  }
  private int bitField0_;
  public static final int ACCESS_TOKEN_DATA_FIELD_NUMBER = 1;
  private com.google.ai.edge.gallery.proto.AccessTokenData accessTokenData_;
  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   */
  @java.lang.Override
  public boolean hasAccessTokenData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   */
  @java.lang.Override
  public com.google.ai.edge.gallery.proto.AccessTokenData getAccessTokenData() {
    return accessTokenData_ == null ? com.google.ai.edge.gallery.proto.AccessTokenData.getDefaultInstance() : accessTokenData_;
  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   */
  private void setAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
    value.getClass();
  accessTokenData_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
    value.getClass();
  if (accessTokenData_ != null &&
        accessTokenData_ != com.google.ai.edge.gallery.proto.AccessTokenData.getDefaultInstance()) {
      accessTokenData_ =
        com.google.ai.edge.gallery.proto.AccessTokenData.newBuilder(accessTokenData_).mergeFrom(value).buildPartial();
    } else {
      accessTokenData_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
   */
  private void clearAccessTokenData() {  accessTokenData_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.ai.edge.gallery.proto.UserData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.ai.edge.gallery.proto.UserData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.ai.edge.gallery.proto.UserData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.google.ai.edge.gallery.proto.UserData prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.google.ai.edge.gallery.proto.UserData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.ai.edge.gallery.proto.UserData, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.ai.edge.gallery.proto.UserData)
      com.google.ai.edge.gallery.proto.UserDataOrBuilder {
    // Construct using com.google.ai.edge.gallery.proto.UserData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
     */
    @java.lang.Override
    public boolean hasAccessTokenData() {
      return instance.hasAccessTokenData();
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
     */
    @java.lang.Override
    public com.google.ai.edge.gallery.proto.AccessTokenData getAccessTokenData() {
      return instance.getAccessTokenData();
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
     */
    public Builder setAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
      copyOnWrite();
      instance.setAccessTokenData(value);
      return this;
      }
    /**
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
     */
    public Builder setAccessTokenData(
        com.google.ai.edge.gallery.proto.AccessTokenData.Builder builderForValue) {
      copyOnWrite();
      instance.setAccessTokenData(builderForValue.build());
      return this;
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
     */
    public Builder mergeAccessTokenData(com.google.ai.edge.gallery.proto.AccessTokenData value) {
      copyOnWrite();
      instance.mergeAccessTokenData(value);
      return this;
    }
    /**
     * <code>.com.google.ai.edge.gallery.proto.AccessTokenData access_token_data = 1;</code>
     */
    public Builder clearAccessTokenData() {  copyOnWrite();
      instance.clearAccessTokenData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.google.ai.edge.gallery.proto.UserData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.ai.edge.gallery.proto.UserData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "accessTokenData_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.google.ai.edge.gallery.proto.UserData> parser = PARSER;
        if (parser == null) {
          synchronized (com.google.ai.edge.gallery.proto.UserData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.google.ai.edge.gallery.proto.UserData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.google.ai.edge.gallery.proto.UserData)
  private static final com.google.ai.edge.gallery.proto.UserData DEFAULT_INSTANCE;
  static {
    UserData defaultInstance = new UserData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserData.class, defaultInstance);
  }

  public static com.google.ai.edge.gallery.proto.UserData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserData> PARSER;

  public static com.google.protobuf.Parser<UserData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

